[project]
name = "test-0823-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "duncan0223", email = "duncan0223@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "google-genai>=2.19.0",
]

[project.scripts]
test-0823-a = "test_0823_a:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
